/* LEOGO Admin Data Tools — safe export and deletion helpers. */
(function(){
'use strict';
if(window.__leogoAdminDataTools)return; window.__leogoAdminDataTools=true;
const SUPABASE_URL='https://twpiloiiigdghwcdjbnj.supabase.co';
const SUPABASE_KEY='sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const TABLES=['notifications','order_status_history','premium_profile_chat_messages','premium_profile_media_changes','premium_profile_daily_requests','premium_profile_daily_acceptances','premium_profile_gallery'];
const LABELS={notifications:'Notifications',order_status_history:'Order Status History',premium_profile_chat_messages:'Premium Chat Messages',premium_profile_media_changes:'Premium Media Changes',premium_profile_daily_requests:'Premium Daily Requests',premium_profile_daily_acceptances:'Premium Daily Acceptances',premium_profile_gallery:'Premium Profile Gallery'};
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function msg(t,ok){const e=document.getElementById('adtMsg');if(e)e.innerHTML='<div style="padding:10px;border-radius:9px;background:'+(ok?'#ecfdf3;color:#166534':'#fef2f2;color:#991b1b')+'">'+esc(t)+'</div>'}
function inject(){if(document.getElementById('adminDataTools'))return;const d=document.createElement('section');d.id='adminDataTools';d.className='card';d.innerHTML='<div class="toolbar"><div><h2 style="margin:0">Data Management & Export</h2><div class="muted">Export selected operational data or permanently remove disposable records.</div></div></div><div style="display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:end;margin-top:14px"><label style="margin:0">Data type<select id="adtTable" style="margin-top:5px"></select></label><button id="adtExport" class="light">📊 EXPORT EXCEL</button><button id="adtDelete" class="danger">🗑️ DELETE DATA</button></div><div id="adtMsg" style="margin-top:10px"></div><div class="notice" style="margin-top:10px">Protected: customer accounts, products, sellers, orders, payments, vehicles, provider records and identity documents are not exposed to this deletion tool.</div>';const host=document.querySelector('main');(host||document.body).appendChild(d);const s=d.querySelector('#adtTable');s.innerHTML='<option value="">Select data</option>'+TABLES.map(t=>'<option value="'+t+'">'+LABELS[t]+'</option>').join('');d.querySelector('#adtExport').onclick=exportExcel;d.querySelector('#adtDelete').onclick=deleteData}
async function admin(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;const q=await sb.rpc('leogo_is_admin');return !q.error&&q.data===true}
async function rows(table){const q=await sb.from(table).select('*').order('created_at',{ascending:false}).limit(5000);if(q.error)throw q.error;return q.data||[]}
async function loadXLSX(){if(window.XLSX)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function exportExcel(){try{const table=document.getElementById('adtTable').value;if(!table)return msg('Select a data type first.',false);if(!await admin())return msg('Admin access is required.',false);const data=await rows(table);if(!data.length)return msg('There is no data to export.',false);await loadXLSX();const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'LEOGO Data');XLSX.writeFile(wb,'LEOGO_'+table+'_'+new Date().toISOString().slice(0,10)+'.xlsx');msg(data.length+' records exported to Excel.',true)}catch(e){msg(e.message||'Export failed.',false)}}
async function deleteData(){try{const table=document.getElementById('adtTable').value;if(!table)return msg('Select a data type first.',false);if(!await admin())return msg('Admin access is required.',false);if(!confirm('WARNING: This permanently deletes ALL '+(LABELS[table]||table)+'. Continue?'))return;const token=prompt('Type DELETE to confirm permanent deletion:');if(token!=='DELETE')return msg('Deletion cancelled.',false);const q=await sb.rpc('leogo_admin_clear_disposable_data',{p_table_name:table});if(q.error)throw q.error;msg('Data deleted successfully.',true)}catch(e){msg(e.message||'Deletion failed.',false)}}
function init(){inject()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
