/* LEOGO Admin Data Tools — safe export and deletion helpers. */
(function(){
'use strict';
if(window.__leogoAdminDataTools)return; window.__leogoAdminDataTools=true;
const SUPABASE_URL='https://twpiloiiigdghwcdjbnj.supabase.co';
const SUPABASE_KEY='sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const TABLES=['notifications','order_status_history','premium_profile_chat_messages','premium_profile_media_changes','premium_profile_daily_requests','premium_profile_daily_acceptances','premium_profile_gallery'];
const LABELS={notifications:'Notifications',order_status_history:'Order Status History',premium_profile_chat_messages:'Premium Chat Messages',premium_profile_media_changes:'Premium Media Changes',premium_profile_daily_requests:'Premium Daily Requests',premium_profile_daily_acceptances:'Premium Daily Acceptances',premium_profile_gallery:'Premium Profile Gallery'};
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function getHost(){return document.querySelector('main')||document.body}
function inject(){if(document.getElementById('adminDataTools'))return;const d=document.createElement('section');d.id='adminDataTools';d.className='card';d.style.cssText='margin-top:16px';d.innerHTML='<div class="toolbar"><div><h2 style="margin:0">Data Management & Export</h2><div class="muted">Export operational data to Excel or permanently delete selected disposable records.</div></div></div><div style="display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:end;margin-top:14px"><label style="margin:0">Data type<select id="adtTable" style="margin-top:5px"><option value="">Select data</option></select></label><button id="adtExport" class="light">📊 EXPORT EXCEL</button><button id="adtDelete" class="danger">🗑️ DELETE DATA</button></div><div id="adtMsg" style="margin-top:10px"></div><div class="notice" style="margin-top:10px">Only disposable operational/history tables are offered here. Core accounts, products, sellers, orders, payments and identity records are protected from this tool.</div>';getHost().appendChild(d);const sel=d.querySelector('#adtTable');TABLES.forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=LABELS[t]||t;sel.appendChild(o)});d.querySelector('#adtExport').onclick=exportExcel;d.querySelector('#adtDelete').onclick=deleteData}
function msg(t,ok){const e=document.getElementById('adtMsg');if(e)e.innerHTML='<div class="'+(ok?'success':'error')+'" style="padding:10px;border-radius:9px">'+esc(t)+'</div>'}
async function admin(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;const {data}=await sb.rpc('leogo_is_admin');return !!data}
async function rows(table){const q=await sb.from(table).select('*').order('created_at',{ascending:false}).limit(5000);if(q.error)throw q.error;return q.data||[]}
function csv(rows){if(!rows.length)return '';const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];const val=v=>{if(v==null)return '';if(typeof v==='object')v=JSON.stringify(v);return '"'+String(v).replace(/"/g,'""')+'"'};return [cols.map(val).join(','),...rows.map(r=>cols.map(c=>val(r[c])).join(','))].join('\r\n')}
async function exportExcel(){try{const table=document.getElementById('adtTable').value;if(!table)return msg('Select a data type first.',false);if(!await admin())return msg('Admin access is required.',false);const data=await rows(table);if(!data.length)return msg('There is no data to export for this selection.',false);const blob=new Blob([csv(data)],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='LEOGO_'+table+'_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);msg(data.length+' records exported. Open the CSV with Microsoft Excel.',true)}catch(e){msg(e.message||'Export failed.',false)}}
async function deleteData(){try{const table=document.getElementById('adtTable').value;if(!table)return msg('Select a data type first.',false);if(!await admin())return msg('Admin access is required.',false);const yes=confirm('WARNING: This permanently deletes ALL records in '+(LABELS[table]||table)+'. Continue?');if(!yes)return;const token=prompt('Type DELETE to confirm permanent deletion:');if(token!=='DELETE')return msg('Deletion cancelled.',false);const q=await sb.rpc('leogo_admin_clear_disposable_data',{p_table_name:table});if(q.error)throw q.error;msg('Data deleted successfully.',true)}catch(e){msg(e.message||'Deletion failed.',false)}}
function init(){inject()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
