(function(){'use strict';
if(window.__leogoPremiumProfileApplicationReview)return;window.__leogoPremiumProfileApplicationReview=true;
const URL='https://twpiloiiigdghwcdjbnj.supabase.co',KEY='sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX',sb=window.supabase.createClient(URL,KEY);
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function msg(t,ok){return '<div class="msg '+(ok?'success':'error')+'">'+esc(t)+'</div>'}
async function signed(path){if(!path)return null;const q=await sb.storage.from('premium-private').createSignedUrl(path,300);if(q.error)throw q.error;return q.data?.signedUrl||null}
async function reviewPayment(id,decision){const q=await sb.rpc('admin_review_premium_profile_payment',{p_payment_id:id,p_decision:decision});if(q.error){alert(q.error.message);return}await loadApplications()}
async function reviewApplication(id,decision){let reason='';if(decision==='rejected'){reason=prompt('Enter the rejection reason for this Premium Profile application:')||'';if(!reason.trim())return}const q=await sb.rpc('admin_review_premium_profile_application',{p_application_id:id,p_decision:decision,p_rejection_reason:reason.trim()});if(q.error){alert(q.error.message);return}await loadApplications()}
async function viewDocs(app){try{const [id,passport]=await Promise.all([signed(app.id_picture_path),signed(app.passport_photo_path)]);let html='<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">';if(id)html+='<div><b>ID Picture</b><br><img src="'+esc(id)+'" style="max-width:100%;max-height:420px;object-fit:contain;border:1px solid #e5e7eb;border-radius:12px;margin-top:8px"></div>';if(passport)html+='<div><b>Passport Photo</b><br><img src="'+esc(passport)+'" style="max-width:100%;max-height:420px;object-fit:contain;border:1px solid #e5e7eb;border-radius:12px;margin-top:8px"></div>';html+='</div>';const m=$('modal'),t=$('modalTitle'),b=$('modalBody');if(m&&t&&b){t.textContent='Premium Profile Documents';b.innerHTML=html;m.classList.remove('hidden')}}catch(e){alert(e.message)}}
async function loadApplications(){const host=$('premiumProfileApplicationReviewArea');if(!host)return;host.innerHTML='<div class="muted">Loading Premium Profile applications…</div>';const q=await sb.from('premium_profile_applications').select('*').order('updated_at',{ascending:false});if(q.error){host.innerHTML=msg(q.error.message);return}const apps=q.data||[];if(!apps.length){host.innerHTML='<div class="empty">No Premium Profile applications have been submitted yet.</div>';return}const ids=apps.map(a=>a.id);const p=await sb.from('premium_profile_payments').select('*').in('application_id',ids).order('created_at',{ascending:false});if(p.error){host.innerHTML=msg(p.error.message);return}const payMap={};(p.data||[]).forEach(x=>{if(!payMap[x.application_id])payMap[x.application_id]=x});host.innerHTML='<div class="table-wrap"><table class="table" style="min-width:1250px"><thead><tr><th>Applicant</th><th>Profile Details</th><th>Identity</th><th>Payment</th><th>Status</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>'+apps.map(a=>{const pay=payMap[a.id],st=String(a.status||'draft'),ps=pay?.status||'not submitted';let actions='';if(st==='pending'){if(pay?.status==='pending')actions+='<button class="light" data-pay="'+esc(pay.id)+'" data-decision="paid">CONFIRM PAYMENT</button><button class="danger" data-pay="'+esc(pay.id)+'" data-decision="rejected">REJECT PAYMENT</button>';actions+='<button class="approve" data-app="'+esc(a.id)+'" data-decision="approved">APPROVE PROFILE</button><button class="danger" data-app="'+esc(a.id)+'" data-decision="rejected">REJECT PROFILE</button>'}else if(st==='rejected'){actions+='<button class="light" data-app="'+esc(a.id)+'" data-decision="approved">APPROVE AFTER REVIEW</button>'}actions+='<button class="blue" data-doc="'+esc(a.id)+'">VIEW ID / PASSPORT</button>';return '<tr><td><b>'+esc(a.username)+'</b><br>'+esc(a.contact)+'</td><td><b>Official:</b> '+esc(a.official_name)+'<br><b>Age:</b> '+esc(a.age)+' · <b>Sex:</b> '+esc(a.sex)+'<br><b>Location:</b> '+esc(a.location)+'<br><b>Orientation:</b> '+esc(a.orientation)+'<br><span class="muted">'+esc(a.description||'No description')+'</span></td><td><b>ID No:</b> '+esc(a.id_number)+'<br><button class="light" data-doc="'+esc(a.id)+'">VIEW DOCUMENTS</button></td><td><b>KSh '+Number(pay?.amount||0).toLocaleString()+'</b><br>'+esc(pay?.reference||'—')+'<br><span class="pill '+(ps==='paid'?'green':'')+'">'+esc(ps)+'</span></td><td><span class="pill '+(st==='approved'?'green':st==='rejected'?'red':'')+'">'+esc(st)+'</span>'+(a.rejection_reason?'<br><span class="muted">'+esc(a.rejection_reason)+'</span>':'')+'</td><td>'+esc(a.submitted_at?new Date(a.submitted_at).toLocaleString():'—')+'</td><td><div class="actions">'+actions+'</div></td></tr>'}).join('')+'</tbody></table></div>'}
document.addEventListener('click',function(e){const b=e.target.closest('[data-app],[data-pay],[data-doc]');if(!b)return;if(b.dataset.app){reviewApplication(b.dataset.app,b.dataset.decision)}else if(b.dataset.pay){reviewPayment(b.dataset.pay,b.dataset.decision)}else if(b.dataset.doc){const id=b.dataset.doc;sb.from('premium_profile_applications').select('*').eq('id',id).maybeSingle().then(q=>q.data&&viewDocs(q.data))}});
window.initPremiumProfileApplicationReview=function(){const area=$('premiumArea');if(!area)return;if($('premiumProfileApplicationReviewCard')){loadApplications();return}const card=document.createElement('div');card.id='premiumProfileApplicationReviewCard';card.className='card';card.innerHTML='<div class="toolbar"><div><h2 style="margin:0">Premium Profile Application Approval</h2><div class="muted">This is the application queue submitted by Premium Profile applicants. Payment must be confirmed before approval.</div></div><button class="light" id="refreshPremiumProfileApplications">↻ REFRESH</button></div><div id="premiumProfileApplicationReviewArea" style="margin-top:12px"></div>';area.insertBefore(card,area.firstChild);$('refreshPremiumProfileApplications').onclick=loadApplications;loadApplications()};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(window.initPremiumProfileApplicationReview,0));else setTimeout(window.initPremiumProfileApplicationReview,0);
})();
