/* LEOGO RFQ - customer dashboard side. Isolated from marketplace/auth/cart/checkout. */
(function(){
  if(window.__leogoCustomerRfqInstalled)return;
  window.__leogoCustomerRfqInstalled=true;
  const sb=window.supabase.createClient('https://twpiloiiigdghwcdjbnj.supabase.co','sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX');
  const esc=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const money=v=>'KSh '+Number(v||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
  function ensure(){
    const dash=document.getElementById('dashboard');if(!dash)return false;
    let p=document.getElementById('leogoCustomerRfqPanel');
    if(!p){p=document.createElement('div');p.id='leogoCustomerRfqPanel';p.className='panel';p.style.marginTop='18px';p.innerHTML='<div class="section-head"><div><h2>📋 My Quotation Requests</h2><div class="muted">Compare quotations submitted by service providers assigned to your request.</div></div><button class="btn light" id="customerRfqRefresh">↻ Refresh</button></div><div id="customerRfqArea"><div class="empty">Loading…</div></div>';dash.appendChild(p);document.getElementById('customerRfqRefresh').onclick=load;}
    return true;
  }
  async function load(){
    if(!ensure())return;const area=document.getElementById('customerRfqArea');if(!area)return;area.innerHTML='<div class="empty">Loading quotations…</div>';
    const {data:{session}}=await sb.auth.getSession();if(!session){area.innerHTML='<div class="empty">Log in as a customer to view quotation requests.</div>';return;}
    const j=await sb.from('service_jobs').select('id,service_id,location,landmark,service_description,preferred_date,preferred_time,budget,urgency,status,created_at').eq('customer_id',session.user.id).eq('request_type','quotation_request').order('created_at',{ascending:false}).limit(100);
    if(j.error){area.innerHTML='<div class="notice error">'+esc(j.error.message)+'</div>';return;}
    const jobs=j.data||[];if(!jobs.length){area.innerHTML='<div class="empty">You have not submitted any quotation requests yet.</div>';return;}
    const q=await sb.rpc('get_customer_service_quotes');if(q.error){area.innerHTML='<div class="notice error">'+esc(q.error.message)+'</div>';return;}
    const quotes=q.data||[];
    area.innerHTML=jobs.map(job=>{const qs=quotes.filter(x=>x.service_job_id===job.id);const first=qs[0];return `<div style="border:1px solid #e5e7eb;border-radius:14px;padding:15px;margin-bottom:14px"><div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap"><div><h3 style="margin:0">${esc(first?.service_name||'Service')}</h3><div class="muted">${esc(first?.service_category||'')} · Requested ${esc(new Date(job.created_at).toLocaleString('en-KE'))}</div></div><span class="pill orange">${esc(job.status||'Requested')}</span></div><div class="muted" style="margin:9px 0">Location: ${esc(job.location||'—')} ${job.landmark?' · '+esc(job.landmark):''}<br>Request: ${esc(job.service_description||'—')}</div>${qs.length?`<div style="display:grid;gap:10px">${qs.map(x=>`<div style="background:#f8fafc;border-radius:12px;padding:13px;border:1px solid #e5e7eb"><div style="display:flex;justify-content:space-between;gap:8px;align-items:start"><div><b>${esc(x.provider_name||'LEOGO Service Provider')}</b><div class="muted">${esc(x.provider_location||'Local provider')}</div></div><strong style="font-size:20px;color:#07152f">${money(x.quote_amount)}</strong></div><div style="margin-top:8px"><b>Estimated duration:</b> ${esc(x.estimated_duration||'Not specified')} · <b>Valid:</b> ${x.validity_days==null?'Not specified':esc(x.validity_days)+' days'}</div><div class="muted" style="margin-top:6px">${esc(x.notes||'No additional notes.')}</div><button class="btn orange" style="margin-top:10px" onclick='window.__leogoDownloadQuote(${JSON.stringify(x)})'>⬇ Download Quotation</button></div>`).join('')}</div>`:'<div class="empty" style="padding:20px">No provider quotations submitted yet. LEOGO Admin may still be assigning providers.</div>'}</div>`}).join('');
  }
  window.__leogoDownloadQuote=async function(data){
    const loadPdf=()=>new Promise((resolve,reject)=>{if(window.jspdf?.jsPDF)return resolve(window.jspdf.jsPDF);const s=document.createElement('script');s.src='https://unpkg.com/jspdf@4.2.1/dist/jspdf.umd.min.js';s.onload=()=>window.jspdf?.jsPDF?resolve(window.jspdf.jsPDF):reject(new Error('PDF library unavailable'));s.onerror=()=>reject(new Error('PDF library failed to load'));document.head.appendChild(s)});
    try{const JsPDF=await loadPdf();const doc=new JsPDF();let y=18;const line=(t,size=10,bold=false)=>{doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);const lines=doc.splitTextToSize(String(t||''),180);doc.text(lines,15,y);y+=lines.length*(size*.48)+5;if(y>275){doc.addPage();y=18;}};line('LEOGO DIGITAL MARKET',18,true);line('SERVICE QUOTATION',14,true);line('Quotation Date: '+new Date(data.quote_created_at).toLocaleDateString('en-KE'));line('Customer: '+(data.customer_name||'LEOGO Customer'),11,true);line('Customer Contact: '+(data.contact_phone||'Not provided'));line('Service: '+(data.service_name||'Service'),12,true);line('Category: '+(data.service_category||''));line('Customer Request: '+(data.service_description||''));line('Location: '+(data.location||'')+(data.landmark?' | Landmark: '+data.landmark:''));line('Provider: '+(data.provider_name||'LEOGO Service Provider'));line('Provider Location: '+(data.provider_location||''));line('Quotation Amount: '+money(data.quote_amount),13,true);line('Estimated Duration: '+(data.estimated_duration||'Not specified'));line('Quotation Validity: '+(data.validity_days==null?'Not specified':data.validity_days+' days'));line('Notes / Scope: '+(data.notes||'None'));line('Status: Submitted');line('Generated from the LEOGO customer dashboard.');doc.save('LEOGO-Quotation-'+String(data.quote_id).slice(0,8)+'.pdf');}catch(e){alert('Could not generate PDF. Please try again. '+e.message)}
  };
  const obs=new MutationObserver(()=>{const d=document.getElementById('dashboard');if(d?.classList.contains('active'))load()});obs.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});setInterval(()=>{const d=document.getElementById('dashboard');if(d?.classList.contains('active'))ensure()},2500);
})();