/* LEOGO NOTIFICATIONS — shared unread notification center for all signed-in roles. */
(function(){
  'use strict';
  if(window.__leogoNotificationsInstalled)return;
  window.__leogoNotificationsInstalled=true;
  const URL='https://twpiloiiigdghwcdjbnj.supabase.co',KEY='sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX',sb=window.supabase.createClient(URL,KEY);
  let timer=null,open=false;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const css=`#leogoNotificationBell{position:relative;border:1px solid #e5e7eb;background:#fff;border-radius:12px;width:44px;height:44px;display:grid;place-items:center;font-size:21px;cursor:pointer;z-index:1000}#leogoNotificationBadge{position:absolute;right:-5px;top:-5px;min-width:20px;height:20px;padding:0 5px;border-radius:999px;background:#ff7a00;color:#fff;font:900 11px/20px system-ui;text-align:center;border:2px solid #fff}#leogoNotificationPanel{position:fixed;right:18px;top:72px;width:min(390px,calc(100vw - 24px));max-height:75vh;background:#fff;border:1px solid #e5e7eb;border-radius:16px;box-shadow:0 18px 60px rgba(7,21,47,.22);z-index:1001;overflow:hidden}#leogoNotificationPanel .ln-head{display:flex;justify-content:space-between;align-items:center;padding:14px 15px;border-bottom:1px solid #e5e7eb;background:#f8fafc}#leogoNotificationPanel .ln-list{max-height:60vh;overflow:auto}#leogoNotificationPanel .ln-item{padding:13px 15px;border-bottom:1px solid #eef0f3;cursor:pointer}#leogoNotificationPanel .ln-item:hover{background:#f8fafc}#leogoNotificationPanel .ln-item.unread{background:#fff7ed;border-left:4px solid #ff7a00}#leogoNotificationPanel .ln-title{font-weight:900;color:#101828;font-size:14px}#leogoNotificationPanel .ln-msg{font-size:13px;color:#475467;margin-top:4px;line-height:1.4}#leogoNotificationPanel .ln-time{font-size:10px;color:#98a2b3;margin-top:6px}#leogoNotificationPanel .ln-foot{padding:10px 15px;border-top:1px solid #e5e7eb;text-align:right}.ln-action{border:0;background:#eef3fb;color:#07152f;border-radius:9px;padding:8px 10px;font-weight:800;cursor:pointer}.ln-empty{text-align:center;padding:35px 15px;color:#667085;font-size:13px}`;
  function styles(){if(document.getElementById('leogoNotificationStyles'))return;const s=document.createElement('style');s.id='leogoNotificationStyles';s.textContent=css;document.head.appendChild(s)}
  function ensure(){if(document.getElementById('leogoNotificationBell'))return;styles();const host=document.createElement('div');host.style.cssText='display:flex;align-items:center;margin-left:4px';host.innerHTML='<button id="leogoNotificationBell" aria-label="Notifications" title="Notifications">🔔<span id="leogoNotificationBadge" class="hidden">0</span></button>';const target=document.querySelector('.nav-actions')||document.querySelector('header .container')||document.body;target.appendChild(host);document.getElementById('leogoNotificationBell').onclick=e=>{e.stopPropagation();toggle()};document.addEventListener('click',e=>{if(open&&!e.target.closest('#leogoNotificationPanel')&&!e.target.closest('#leogoNotificationBell'))close()})}
  function fmt(v){try{return new Date(v).toLocaleString('en-KE',{dateStyle:'medium',timeStyle:'short'})}catch{return ''}}
  async function session(){return (await sb.auth.getSession()).data?.session||null}
  async function count(){const s=await session();if(!s){hide();return}const q=await sb.rpc('get_my_unread_notification_count');if(q.error){console.warn('LEOGO notifications:',q.error);return}const n=Number(q.data||0),b=document.getElementById('leogoNotificationBadge');if(b){b.textContent=n>99?'99+':String(n);b.classList.toggle('hidden',n===0)}}
  async function load(){const s=await session();if(!s)return;const q=await sb.rpc('get_my_notifications',{p_limit:50});const list=document.querySelector('#leogoNotificationPanel .ln-list');if(!list)return;if(q.error){list.innerHTML='<div class="ln-empty">Notifications are temporarily unavailable.</div>';return}const rows=(q.data||[]).filter(x=>!x.is_read);list.innerHTML=rows.length?rows.map(n=>'<div class="ln-item unread" data-id="'+esc(n.id)+'" data-link="'+esc(n.link||'')+'"><div class="ln-title">'+esc(n.title)+'</div><div class="ln-msg">'+esc(n.message)+'</div><div class="ln-time">'+esc(fmt(n.created_at))+'</div></div>').join(''):'<div class="ln-empty">You have no unread notifications.</div>';list.querySelectorAll('.ln-item').forEach(x=>x.onclick=async()=>{await sb.rpc('mark_notification_read',{p_notification_id:x.dataset.id});const link=x.dataset.link;close();await count();if(link)window.location.href=link;else if(typeof window.loadAllProducts==='function')window.loadAllProducts()})}
  function panel(){document.getElementById('leogoNotificationPanel')?.remove();const p=document.createElement('div');p.id='leogoNotificationPanel';p.innerHTML='<div class="ln-head"><b>Notifications</b><button class="ln-action" id="lnMarkAll">Mark all as read</button></div><div class="ln-list"><div class="ln-empty">Loading…</div></div><div class="ln-foot"><span style="font-size:11px;color:#98a2b3">Unread notifications</span></div>';document.body.appendChild(p);document.getElementById('lnMarkAll').onclick=async()=>{await sb.rpc('mark_all_notifications_read');await load();await count()};load()}
  function toggle(){open=!open;if(open)panel();else close()}
  function close(){open=false;document.getElementById('leogoNotificationPanel')?.remove()}
  function hide(){document.getElementById('leogoNotificationBell')?.parentElement?.remove();close()}
  async function init(){ensure();await count();if(timer)clearInterval(timer);timer=setInterval(count,15000)}
  sb.auth.onAuthStateChange(()=>setTimeout(init,100));
  window.LEOGONotifications={refresh:count,open:()=>{open=true;panel()}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();