/* LEOGO PREMIUM PROFILE CHAT — short private conversation before acceptance. */
(function(){
  'use strict';
  if(window.__leogoPremiumChatInstalled)return;
  window.__leogoPremiumChatInstalled=true;
  const URL='https://twpiloiiigdghwcdjbnj.supabase.co',KEY='sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX',sb=window.supabase.createClient(URL,KEY);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  let timer=null,currentChat=null,currentUser=null;
  function ensureStyles(){if(document.getElementById('leogoPremiumChatStyles'))return;const s=document.createElement('style');s.id='leogoPremiumChatStyles';s.textContent='.lpc-backdrop{position:fixed;inset:0;background:rgba(7,21,47,.58);z-index:99999;display:flex;align-items:center;justify-content:center;padding:14px}.lpc-card{width:min(560px,100%);max-height:min(760px,94vh);background:#fff;border-radius:20px;box-shadow:0 20px 60px rgba(0,0,0,.25);display:flex;flex-direction:column;overflow:hidden}.lpc-head{padding:16px 18px;border-bottom:1px solid #e5e7eb;display:flex;justify-content:space-between;align-items:center}.lpc-messages{padding:14px;background:#f8fafc;overflow:auto;flex:1;min-height:300px}.lpc-msg{max-width:82%;padding:9px 11px;border-radius:14px;margin:7px 0;line-height:1.4;font-size:14px;white-space:pre-wrap;word-break:break-word}.lpc-me{margin-left:auto;background:#ff7a00;color:#fff;border-bottom-right-radius:4px}.lpc-them{margin-right:auto;background:#fff;border:1px solid #e5e7eb;color:#101828;border-bottom-left-radius:4px}.lpc-compose{padding:12px;border-top:1px solid #e5e7eb;background:#fff}.lpc-compose textarea{width:100%;resize:none;min-height:70px;border:1px solid #d0d5dd;border-radius:12px;padding:10px;font:inherit;box-sizing:border-box}.lpc-foot{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:8px}.lpc-muted{font-size:11px;color:#667085}.lpc-close{border:0;background:#eef3fb;color:#07152f;border-radius:9px;padding:8px 11px;font-weight:900;cursor:pointer}.lpc-open{border:0;background:#ff7a00;color:#fff;border-radius:10px;padding:9px 12px;font-weight:900;cursor:pointer}.lpc-open.light{background:#eef3fb;color:#07152f}.lpc-list{display:grid;gap:9px}.lpc-list-item{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:12px;border:1px solid #e5e7eb;border-radius:12px;background:#fff}';document.head.appendChild(s)}
  async function session(){const q=await sb.auth.getSession();currentUser=q.data?.session?.user||null;return currentUser}
  async function open(requestId,type){
    if(!(await session())){alert('Please log in again.');return}
    const q=await sb.rpc('premium_profile_open_chat',{p_request_id:requestId,p_type:type});
    if(q.error){alert(q.error.message);return}
    const r=q.data?.[0]||q.data;if(!r?.chat_id){alert('Conversation could not be opened.');return}
    currentChat=r.chat_id;ensureStyles();renderModal(type,r.request_status);await loadMessages(true);startPolling();
  }
  function renderModal(type,status){document.getElementById('leogoPremiumChatModal')?.remove();const m=document.createElement('div');m.id='leogoPremiumChatModal';m.className='lpc-backdrop';m.innerHTML='<div class="lpc-card"><div class="lpc-head"><div><div style="font-size:10px;font-weight:900;color:#ff7a00;letter-spacing:.8px">LEOGO PREMIUM • PRIVATE CHAT</div><b>'+((currentUser&&window.__leogoPremiumChatRole==='owner')?'Premium Customer':'Premium Profile Owner')+'</b><div class="lpc-muted">Short conversation · request is '+esc(status)+'</div></div><button class="lpc-close" id="lpcClose">✕</button></div><div id="lpcMessages" class="lpc-messages"><div class="lpc-muted">Loading conversation…</div></div><div class="lpc-compose"><textarea id="lpcInput" maxlength="500" placeholder="Write a short message (max 500 characters)…"></textarea><div class="lpc-foot"><span id="lpcCount" class="lpc-muted">0/500</span><button id="lpcSend" class="lpc-open">SEND MESSAGE</button></div><div class="lpc-muted" style="margin-top:7px">Up to 10 messages per person. Contact details remain protected until the request is accepted.</div></div></div>';document.body.appendChild(m);document.getElementById('lpcClose').onclick=close;document.getElementById('lpcSend').onclick=send;document.getElementById('lpcInput').oninput=e=>document.getElementById('lpcCount').textContent=e.target.value.length+'/500';m.onclick=e=>{if(e.target===m)close()};}
  function close(){if(timer)clearInterval(timer);timer=null;currentChat=null;document.getElementById('leogoPremiumChatModal')?.remove()}
  async function loadMessages(scroll){if(!currentChat)return;const q=await sb.rpc('premium_profile_chat_list',{p_chat_id:currentChat});if(q.error){const box=document.getElementById('lpcMessages');if(box)box.innerHTML='<div class="lpc-muted">This conversation is closed.</div>';return}const box=document.getElementById('lpcMessages');if(!box)return;const rows=q.data||[];box.innerHTML=rows.length?rows.map(x=>'<div class="lpc-msg '+(x.sender_id===currentUser?.id?'lpc-me':'lpc-them')+'">'+esc(x.body)+'<div style="font-size:10px;opacity:.72;margin-top:4px">'+esc(new Date(x.created_at).toLocaleString())+'</div></div>').join(''):'<div class="lpc-muted" style="text-align:center;padding:35px 10px">No messages yet. Start the conversation.</div>';if(scroll)box.scrollTop=box.scrollHeight}
  function startPolling(){if(timer)clearInterval(timer);timer=setInterval(()=>loadMessages(false),3000)}
  async function send(){const input=document.getElementById('lpcInput'),btn=document.getElementById('lpcSend');if(!input||!btn)return;const body=input.value.trim();if(!body)return;if(body.length>500){alert('Message must be 1–500 characters.');return}btn.disabled=true;const q=await sb.rpc('premium_profile_send_chat_message',{p_chat_id:currentChat,p_body:body});if(q.error)alert(q.error.message);else{input.value='';document.getElementById('lpcCount').textContent='0/500';await loadMessages(true)}btn.disabled=false}
  async function openMine(){if(!(await session())){alert('Please log in again.');return}const q=await sb.from('premium_profile_chats').select('id,request_type,request_id,updated_at,created_at,premium_profile_id,customer_id,owner_id').or('customer_id.eq.'+currentUser.id+',owner_id.eq.'+currentUser.id).order('updated_at',{ascending:false});if(q.error){alert(q.error.message);return}ensureStyles();const rows=q.data||[];document.getElementById('leogoPremiumChatListModal')?.remove();const m=document.createElement('div');m.id='leogoPremiumChatListModal';m.className='lpc-backdrop';m.innerHTML='<div class="lpc-card"><div class="lpc-head"><div><div style="font-size:10px;font-weight:900;color:#ff7a00">LEOGO PREMIUM</div><b>My Conversations</b></div><button class="lpc-close" id="lpclClose">✕</button></div><div style="padding:14px;overflow:auto"><div class="lpc-list">'+(rows.length?rows.map(r=>'<div class="lpc-list-item"><div><b>'+(r.request_type==='booking'?'Booking request':'Interest request')+'</b><div class="lpc-muted">Last activity: '+esc(new Date(r.updated_at||r.created_at).toLocaleString())+'</div></div><button class="lpc-open light" data-chat-id="'+esc(r.id)+'" data-chat-type="'+esc(r.request_type)+'">OPEN CHAT</button></div>').join(''):'<div class="lpc-muted">No Premium conversations yet. Send an interest or booking request to start one.</div>')+'</div></div></div>';document.body.appendChild(m);document.getElementById('lpclClose').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};m.querySelectorAll('[data-chat-id]').forEach(b=>b.onclick=()=>{m.remove();currentChat=b.dataset.chatId;ensureStyles();renderModal(b.dataset.chatType,'pending/accepted');loadMessages(true);startPolling()})}
  function decorateOwner(){document.querySelectorAll('tr').forEach(row=>{const view=row.querySelector('[data-action="view"][data-id][data-type]');if(!view||row.querySelector('[data-lpc-owner-chat]'))return;const actionCell=view.closest('td')||row;const c=document.createElement('button');c.className='btn light';c.textContent='CHAT';c.dataset.lpcOwnerChat='1';c.dataset.requestId=view.dataset.id;c.dataset.requestType=view.dataset.type;c.style.marginLeft='5px';c.onclick=()=>open(c.dataset.requestId,c.dataset.requestType);actionCell.appendChild(c)});}
  function decorateCustomerDiscovery(){document.querySelectorAll('.lpInterestBtn,.lpBookingBtn').forEach(btn=>{if(btn.dataset.lpcBound)return;btn.dataset.lpcBound='1';});}
  function injectCustomerButton(){const modal=document.getElementById('leogoPremiumModal');if(!modal||modal.dataset.chatButton==='1'||!/Private Premium Area|Access confirmed/i.test(modal.textContent||''))return;const area=Array.from(modal.querySelectorAll('.panel')).find(x=>/Private Premium Area/i.test(x.textContent||''));if(!area)return;modal.dataset.chatButton='1';const b=document.createElement('button');b.className='btn light';b.type='button';b.id='leogoPremiumChatsBtn';b.textContent='💬 MY PREMIUM CONVERSATIONS';b.style.cssText='margin-top:8px';b.onclick=openMine;area.appendChild(b)}
  window.LEOGOPremiumChat={open,openMine};
  const obs=new MutationObserver(()=>{decorateOwner();decorateCustomerDiscovery();injectCustomerButton()});
  function start(){obs.observe(document.body,{childList:true,subtree:true});decorateOwner();decorateCustomerDiscovery();injectCustomerButton()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
