/* LEOGO PREMIUM ACCEPTANCE ADMIN — isolated addon. */
(function(){
'use strict';
if(window.__leogoPremiumAcceptanceAdminInstalled)return;window.__leogoPremiumAcceptanceAdminInstalled=true;
const sb=window.__leogoAdminSB||window.supabase.createClient('https://twpiloiiigdghwcdjbnj.supabase.co','sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'KSh '+Number(v||0).toLocaleString();
async function load(){const host=document.getElementById('premiumAcceptanceAdminAddon');if(!host)return;host.innerHTML='<div class="empty">Loading additional acceptance controls…</div>';const [price,pay]=await Promise.all([sb.from('premium_profile_pricing').select('plan_code,plan_name,price,duration_days,is_active,updated_at').eq('plan_code','acceptance').maybeSingle(),sb.from('premium_profile_acceptance_payments').select('*').order('created_at',{ascending:false}).limit(200)]);if(price.error||pay.error){host.innerHTML='<div class="msg error">Could not load additional acceptance controls.</div>';return;}const p=price.data,rows=pay.data||[];let h='<div class="card" style="margin-top:14px"><div class="toolbar"><div><h3 style="margin:0">Additional Acceptance Pricing</h3><div class="muted">Customer gets 1 free acceptance per day, then pays per additional acceptance. Maximum 4 paid unlocks.</div></div><div class="actions"><input id="lpAdminAcceptancePrice" type="number" min="0" step="0.01" value="'+esc(p?.price??100)+'" style="width:130px"><button class="orange" id="lpSaveAcceptancePrice">SAVE PRICE</button></div></div><div class="muted" style="margin-top:8px">Current price: <b>'+money(p?.price)+'</b> per additional acceptance.</div></div>';
h+='<div class="card"><div class="toolbar"><div><h3 style="margin:0">Additional Acceptance Payments</h3><div class="muted">Confirm customer M-Pesa references before extra acceptance slots are released.</div></div><button class="light" id="lpRefreshAcceptancePayments">↻ REFRESH</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Customer</th><th>Slots</th><th>Amount</th><th>Reference</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>';
if(!rows.length)h+='<tr><td colspan="7"><div class="empty">No additional acceptance payments yet.</div></td></tr>';else rows.forEach(r=>{h+='<tr><td>'+esc(r.customer_id)+'</td><td><b>'+esc(r.acceptance_slots)+'</b></td><td><b>'+money(r.amount)+'</b></td><td><b>'+esc(r.reference)+'</b></td><td>'+new Date(r.created_at).toLocaleString()+'</td><td><span class="pill '+(r.status==='paid'?'green':r.status==='rejected'?'red':'')+'">'+esc(r.status)+'</span></td><td>'+(r.status==='pending'?'<div class="actions"><button class="approve" data-id="'+r.id+'" data-decision="paid">APPROVE</button><button class="danger" data-id="'+r.id+'" data-decision="rejected">REJECT</button></div>':'Reviewed')+'</td></tr>';});
h+='</tbody></table></div></div>';host.innerHTML=h;document.getElementById('lpSaveAcceptancePrice').onclick=async()=>{const v=Number(document.getElementById('lpAdminAcceptancePrice').value);if(!Number.isFinite(v)||v<0)return alert('Enter a valid price.');const q=await sb.rpc('admin_set_premium_profile_price',{p_plan_code:'acceptance',p_price:v});if(q.error)return alert(q.error.message);alert('Additional acceptance price updated.');load();};document.getElementById('lpRefreshAcceptancePayments').onclick=load;host.querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{const q=await sb.rpc('admin_review_premium_profile_acceptance_payment',{p_payment_id:b.dataset.id,p_decision:b.dataset.decision});if(q.error)return alert(q.error.message);load();});}
function inject(){const area=document.getElementById('premiumArea');if(!area||document.getElementById('premiumAcceptanceAdminAddon'))return;const host=document.createElement('div');host.id='premiumAcceptanceAdminAddon';area.appendChild(host);load();}
new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
