/* LEOGO PREMIUM IDENTITY FIX - prevents re-render loop while submitting. */
(function(){
  if(window.__leogoPremiumIdentityFixInstalled)return;
  window.__leogoPremiumIdentityFixInstalled=true;
  const URL='https://twpiloiiigdghwcdjbnj.supabase.co',KEY='sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX',BUCKET='premium-private';
  const sb=window.supabase.createClient(URL,KEY);let busy=false;
  const esc=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  async function session(){return (await sb.auth.getSession()).data?.session||null}
  async function membership(){const s=await session();if(!s)return null;const q=await sb.from('premium_memberships').select('id,status').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();return q.error?null:q.data}
  async function identity(mid){const q=await sb.rpc('get_my_premium_identity_status',{p_membership_id:mid});return q.error?null:(q.data||[])[0]||null}
  function area(){const m=document.getElementById('leogoPremiumModal');if(!m)return null;return Array.from(m.querySelectorAll('.panel')).find(x=>/Premium Membership/i.test(x.textContent||''))||m}
  function form(){return '<div class="panel" style="background:#fff;border:1px solid #dbe3ef"><h4>Premium identity verification</h4><p class="muted" style="font-size:13px">Your identity details are private and are reviewed only by authorized LEOGO staff.</p><div class="field"><label>Full name as it appears on your ID *</label><input id="lpiFixName" maxlength="120"></div><div class="field"><label>Phone number *</label><input id="lpiFixPhone" maxlength="30"></div><div class="field"><label>Identification type *</label><select id="lpiFixType"><option>National ID</option><option>Passport</option><option>Alien ID</option><option>Other</option></select></div><div class="field"><label>Identification number *</label><input id="lpiFixNumber" maxlength="60"></div><div class="field"><label>Picture of ID / passport document <span class="muted">(recommended)</span></label><input id="lpiFixId" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"><div class="muted" style="font-size:12px">Private upload • maximum 5 MB.</div></div><div class="field"><label>Profile picture *</label><input id="lpiFixProfile" type="file" accept="image/jpeg,image/png,image/webp"><div class="muted" style="font-size:12px">Maximum 5 MB.</div></div><div class="field"><label>LEOGO username *</label><input id="lpiFixUsername" maxlength="60"></div><div id="lpiFixMsg"></div><button class="btn orange" id="lpiFixSubmit" style="width:100%">SUBMIT IDENTITY FOR ADMIN REVIEW</button></div>'}
  async function upload(file,kind,uid,mid){if(!file)return null;if(file.size>5242880)throw new Error('File must be 5 MB or smaller.');const ok=kind==='profile'?['image/jpeg','image/png','image/webp']:['image/jpeg','image/png','image/webp','application/pdf'];if(!ok.includes(file.type))throw new Error('Unsupported file type.');const ext=(file.name.split('.').pop()||'bin').toLowerCase().replace(/[^a-z0-9]/g,'');const path=uid+'/'+mid+'/'+kind+'.'+ext;const q=await sb.storage.from(BUCKET).upload(path,file,{contentType:file.type,upsert:true,cacheControl:'3600'});if(q.error)throw q.error;return q.data.path}
  async function submit(mid){if(busy)return;busy=true;const msg=document.getElementById('lpiFixMsg'),btn=document.getElementById('lpiFixSubmit');try{const s=await session();if(!s)throw new Error('Please log in again.');const v=id=>document.getElementById(id)?.value.trim();const name=v('lpiFixName'),phone=v('lpiFixPhone'),type=v('lpiFixType'),num=v('lpiFixNumber'),username=v('lpiFixUsername'),idf=document.getElementById('lpiFixId')?.files?.[0],profile=document.getElementById('lpiFixProfile')?.files?.[0];if(!name||!phone||!type||!num||!username||!profile)throw new Error('Please complete all required fields and upload a profile picture.');btn.disabled=true;btn.textContent='UPLOADING & SUBMITTING…';const ip=await upload(idf,'id-document',s.user.id,mid),pp=await upload(profile,'profile',s.user.id,mid);const q=await sb.rpc('submit_premium_identity',{p_membership_id:mid,p_full_name_as_id:name,p_phone_number:phone,p_id_type:type,p_id_number:num,p_id_document_path:ip,p_profile_photo_path:pp,p_leogo_username:username});if(q.error)throw q.error;const box=document.getElementById('leogoPremiumIdentityFixBox');if(box)box.innerHTML='<div class="notice success"><b>Identity submitted to LEOGO Admin.</b><br>Your payment and identity are now waiting for administrative review.</div>';}catch(e){if(msg)msg.innerHTML='<div class="notice error">'+esc(e.message||'Unable to submit identity.')+'</div>'}finally{busy=false;if(btn){btn.disabled=false;btn.textContent='SUBMIT IDENTITY FOR ADMIN REVIEW'}}}
  async function render(){if(busy)return;const a=area();if(!a||document.getElementById('leogoPremiumIdentityFixBox'))return;const m=await membership();if(!m)return;const i=await identity(m.id);if(i?.status==='pending'||i?.status==='approved')return;const box=document.createElement('div');box.id='leogoPremiumIdentityFixBox';box.style.cssText='margin-top:14px';box.innerHTML=form();a.appendChild(box);document.getElementById('lpiFixSubmit').onclick=()=>submit(m.id)}
  const observer=new MutationObserver(()=>{if(!busy)render()});observer.observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
