/* LEOGO RFQ - provider side. Isolated from existing provider dashboard logic. */
(function(){
  if(window.__leogoProviderRfqInstalled)return;
  window.__leogoProviderRfqInstalled=true;
  const sb=window.supabase.createClient('https://twpiloiiigdghwcdjbnj.supabase.co','sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX');
  const esc=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const money=v=>'KSh '+Number(v||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});
  function inject(){
    if(document.getElementById('leogoProviderRfqPanel'))return;
    const anchor=document.querySelector('.panel h2')?.closest('.panel');
    if(!anchor)return;
    const p=document.createElement('div');p.id='leogoProviderRfqPanel';p.className='panel';
    p.innerHTML='<h2>📋 Assigned Quotation Requests</h2><div class="muted" style="margin-bottom:12px">Quotation requests assigned to you by LEOGO Admin. Submit your quotation for the customer to review.</div><div id="leogoProviderRfqArea"><div class="empty">Loading…</div></div>';
    anchor.parentNode.insertBefore(p,anchor);
    load();
  }
  async function load(){
    const area=document.getElementById('leogoProviderRfqArea');if(!area)return;
    const {data:{session}}=await sb.auth.getSession();if(!session){area.innerHTML='<div class="empty">Please log in.</div>';return;}
    const a=await sb.from('service_rfq_assignments').select('id,service_job_id,status,assigned_at,responded_at').eq('provider_id',session.user.id).order('assigned_at',{ascending:false}).limit(100);
    if(a.error){area.innerHTML='<div class="error">'+esc(a.error.message)+'</div>';return;}
    const assigns=a.data||[];if(!assigns.length){area.innerHTML='<div class="empty">No quotation requests have been assigned to you.</div>';return;}
    const ids=assigns.map(x=>x.service_job_id);const j=await sb.from('service_jobs').select('id,customer_id,service_id,location,landmark,service_description,contact_phone,preferred_date,preferred_time,budget,urgency,status,created_at').in('id',ids).eq('request_type','quotation_request');
    const jobs=new Map((j.data||[]).map(x=>[x.id,x]));
    const serviceIds=[...new Set((j.data||[]).map(x=>x.service_id).filter(Boolean))];let sm=new Map();if(serviceIds.length){const s=await sb.from('services').select('id,name,category').in('id',serviceIds);sm=new Map((s.data||[]).map(x=>[x.id,x]));}
    const q=await sb.from('service_quotes').select('id,service_job_id,quote_amount,estimated_duration,validity_days,notes,status,created_at').eq('provider_id',session.user.id).in('service_job_id',ids);const qm=new Map((q.data||[]).map(x=>[x.service_job_id,x]));
    area.innerHTML=assigns.map(a=>{const x=jobs.get(a.service_job_id);if(!x)return '';const s=sm.get(x.service_id)||{};const quote=qm.get(x.id);return `<div style="border:1px solid #e5e7eb;border-radius:14px;padding:14px;margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap"><div><b>${esc(s.name||'Service')}</b><div class="muted">${esc(s.category||'')} · ${esc(new Date(x.created_at).toLocaleString('en-KE'))}</div></div><span class="pill ${quote?'approved':'pending'}">${esc(quote?.status||a.status)}</span></div><div style="margin-top:10px"><b>Location:</b> ${esc(x.location||'—')} ${x.landmark?' · '+esc(x.landmark):''}</div><div><b>Customer contact:</b> ${esc(x.contact_phone||'—')}</div><div style="margin-top:8px"><b>Request:</b> ${esc(x.service_description||'—')}</div><div class="muted" style="margin-top:6px">Preferred: ${esc(x.preferred_date||'Flexible')} ${esc(x.preferred_time||'')} · Urgency: ${esc(x.urgency||'Not specified')} · Budget: ${x.budget!=null?money(x.budget):'Not specified'}</div>${quote?`<div class="notice" style="margin-top:10px"><b>Submitted quotation:</b> ${money(quote.quote_amount)} · ${esc(quote.estimated_duration||'Duration not specified')} · Valid ${quote.validity_days==null?'unspecified':quote.validity_days+' days'}<br>${esc(quote.notes||'')}</div>`:`<button class="btn orange" style="margin-top:12px" onclick="window.__leogoOpenQuote('${esc(a.id)}','${esc(x.id)}','${esc(s.name||'Service')}')">SUBMIT QUOTATION</button>`}</div>`}).join('')||'<div class="empty">No valid RFQ requests found.</div>';
  }
  window.__leogoOpenQuote=function(assignmentId,jobId,name){
    document.getElementById('leogoProviderQuoteModal')?.remove();const m=document.createElement('div');m.id='leogoProviderQuoteModal';m.className='modal';m.innerHTML=`<div class="modal-card" style="max-width:560px"><div class="modal-head"><div><h2>Submit Quotation</h2><div class="muted">${esc(name)}</div></div><button class="close" id="closeProviderQuote">✕</button></div><div class="field"><label>Quotation Amount (KSh) *</label><input id="pqAmount" type="number" min="0" step="0.01" required></div><div class="field"><label>Estimated Duration</label><input id="pqDuration" placeholder="e.g. 2 hours / 2 days"></div><div class="field"><label>Quotation Valid For (days)</label><input id="pqValidity" type="number" min="0" step="1" value="7"></div><div class="field"><label>Quotation Notes / Scope</label><textarea id="pqNotes" placeholder="Explain what is included, labour, materials, exclusions and any important terms."></textarea></div><div id="pqMsg"></div><button class="btn orange" id="pqSubmit" style="width:100%">Submit Quotation</button></div>`;document.body.appendChild(m);document.getElementById('closeProviderQuote').onclick=()=>m.remove();document.getElementById('pqSubmit').onclick=async()=>{const amount=Number(document.getElementById('pqAmount').value),duration=document.getElementById('pqDuration').value.trim()||null,validity=document.getElementById('pqValidity').value,notes=document.getElementById('pqNotes').value.trim()||null,msg=document.getElementById('pqMsg');if(!Number.isFinite(amount)||amount<0){msg.innerHTML='<div class="error">Enter a valid quotation amount.</div>';return;}const {data:{session}}=await sb.auth.getSession();if(!session)return;const b=document.getElementById('pqSubmit');b.disabled=true;b.textContent='Submitting…';const ins=await sb.from('service_quotes').insert({service_job_id:jobId,assignment_id:assignmentId,provider_id:session.user.id,quote_amount:amount,estimated_duration:duration,validity_days:validity===''?null:Number(validity),notes,status:'submitted'}).select('id').maybeSingle();if(ins.error){b.disabled=false;b.textContent='Submit Quotation';msg.innerHTML='<div class="error">'+esc(ins.error.message)+'</div>';return;}await sb.from('service_rfq_assignments').update({status:'quoted',responded_at:new Date().toISOString()}).eq('id',assignmentId).eq('provider_id',session.user.id);await sb.from('service_jobs').update({status:'Quotation Submitted',updated_at:new Date().toISOString()}).eq('id',jobId);msg.innerHTML='<div class="success">Quotation submitted successfully.</div>';b.textContent='Submitted';setTimeout(()=>{m.remove();load()},900)};
  };
  const boot=setInterval(()=>{if(document.querySelector('.panel h2')){clearInterval(boot);inject()}},300);setTimeout(()=>clearInterval(boot),10000);
})();