/* LEOGO CUSTOMER TRANSPORT MARKETPLACE - approved available vehicles. */
(function(){
  if(window.__leogoTransportMarketplaceInstalled)return;
  window.__leogoTransportMarketplaceInstalled=true;
  const URL='https://twpiloiiigdghwcdjbnj.supabase.co',KEY='sb_publishable_c4iJwLdRuH85e0XuFnkSjg_mdxLN2fX';
  const sbx=window.supabase.createClient(URL,KEY);
  const esc=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const cats=['All','Motorcycle','Passenger Tuk Tuk','Luggage Tuk Tuk','Pickup','Canter','Lorry','Trailer','Other'];
  function category(v){const x=String(v||'').toLowerCase();if(x.includes('motor')||x.includes('boda'))return 'Motorcycle';if(x.includes('passenger')&&x.includes('tuk'))return 'Passenger Tuk Tuk';if(x.includes('luggage')&&x.includes('tuk'))return 'Luggage Tuk Tuk';if(x.includes('pickup'))return 'Pickup';if(x.includes('canter'))return 'Canter';if(x.includes('lorry')||x.includes('truck'))return 'Lorry';if(x.includes('trailer'))return 'Trailer';return 'Other';}
  let vehicles=[],active='All';
  function inject(){
    if(document.getElementById('leogoTransportSection'))return document.getElementById('leogoTransportSection');
    const s=document.createElement('section');s.id='leogoTransportSection';s.innerHTML='<div class="container"><div class="section-head"><div><h2>🚚 Transport & Delivery</h2><div class="muted">Choose an approved LEOGO vehicle for passenger transport, luggage or delivery.</div></div><button class="btn light" id="leogoRefreshTransport">Refresh</button></div><div id="leogoTransportCats" style="display:flex;gap:7px;flex-wrap:wrap;margin:12px 0"></div><div class="grid" id="leogoTransportGrid"><div class="empty">Loading vehicles…</div></div></div>';
    const services=document.getElementById('leogoServicesSection');if(services)services.insertAdjacentElement('afterend',s);else{const p=document.querySelector('#productGrid')?.closest('section');if(p)p.parentNode.insertBefore(s,p);else document.querySelector('#storefront')?.appendChild(s);}document.getElementById('leogoRefreshTransport').onclick=load;return s;
  }
  function render(){const grid=document.getElementById('leogoTransportGrid'),bar=document.getElementById('leogoTransportCats');if(!grid||!bar)return;bar.innerHTML=cats.map(c=>'<button class="btn '+(c===active?'orange':'light')+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>').join('');bar.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.cat;render();});const list=active==='All'?vehicles:vehicles.filter(v=>category(v.vehicle_type)===active);if(!list.length){grid.innerHTML='<div class="empty">No approved vehicles are currently available in this category.</div>';return;}grid.innerHTML=list.map(v=>'<article class="product"><div class="product-img"><div class="placeholder">🚚</div></div><div class="product-body"><div class="pill orange">'+esc(category(v.vehicle_type))+'</div><h3 style="margin-top:8px">'+esc(v.vehicle_type)+'</h3><div class="product-meta">'+esc(v.owner_name)+' · '+esc(v.owner_location)+'</div><div class="product-meta">'+(v.registration?'Registration: '+esc(v.registration)+' · ':'')+(v.capacity_kg!=null?'Capacity: '+esc(v.capacity_kg)+' kg':'')+'</div><div class="product-actions" style="margin-top:10px"><button class="btn orange" data-book="'+esc(v.vehicle_id)+'">Request Booking</button></div></div></article>').join('');grid.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>openBooking(vehicles.find(v=>v.vehicle_id===b.dataset.book)));}
  async function load(){inject();const grid=document.getElementById('leogoTransportGrid');if(!grid)return;grid.innerHTML='<div class="empty">Loading vehicles…</div>';const q=await sbx.rpc('get_public_transport_marketplace');if(q.error){grid.innerHTML='<div class="empty">Unable to load transport providers right now.</div>';return;}vehicles=q.data||[];render();}
  async function openBooking(v){const auth=await sbx.auth.getSession();if(!auth.data?.session){if(typeof window.openAuth==='function')window.openAuth();else alert('Please log in as a customer to request a booking.');return;}document.getElementById('leogoTransportBookingModal')?.remove();const m=document.createElement('div');m.id='leogoTransportBookingModal';m.className='modal';m.innerHTML='<div class="modal-card"><div class="modal-head"><div><h2>Request Transport Booking</h2><div class="muted">'+esc(v.vehicle_type)+' · '+esc(v.owner_name)+'</div></div><button class="close" id="closeTransportBooking">✕</button></div><div class="field"><label>Pickup Location *</label><input id="trPickup" required></div><div class="field"><label>Destination *</label><input id="trDestination" required></div><div class="field"><label>Preferred Date</label><input id="trDate" type="date"></div><div class="field"><label>Preferred Time</label><input id="trTime" type="time"></div><div class="field"><label>Booking Notes</label><textarea id="trNotes" placeholder="Passengers, luggage, parcel details or other requirements"></textarea></div><div id="trMsg"></div><button class="btn orange" id="trSubmit" style="width:100%">Submit Booking Request</button></div>';document.body.appendChild(m);document.getElementById('closeTransportBooking').onclick=()=>m.remove();document.getElementById('trSubmit').onclick=async()=>{const p=document.getElementById('trPickup').value.trim(),d=document.getElementById('trDestination').value.trim(),msg=document.getElementById('trMsg');if(!p||!d){msg.innerHTML='<div class="notice error">Pickup and destination are required.</div>';return;}const u=(await sbx.auth.getSession()).data?.session?.user;if(!u){m.remove();return;}const b=document.getElementById('trSubmit');b.disabled=true;b.textContent='Submitting…';const q=await sbx.from('transport_requests').insert({customer_id:u.id,vehicle_id:v.vehicle_id,pickup_location:p,destination:d,status:'Requested'});if(q.error){b.disabled=false;b.textContent='Submit Booking Request';msg.innerHTML='<div class="notice error">'+esc(q.error.message)+'</div>';return;}msg.innerHTML='<div class="notice success">Booking request submitted. LEOGO will confirm the transport assignment.</div>';b.textContent='Submitted';setTimeout(()=>m.remove(),1000);};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();
